name: library
on:
  push:
    branches: main
  schedule:
    # 周一到周五每天的第6小时运行
    - cron: "* 6 * * 0,4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get dr_Front_ComponentStoryBook code
        uses: actions/checkout@v3
        with:
          repository: ${{secrets.DR_REPOSITORY}}
          token: ${{secrets.DR_TOKEN}}
          ref: development

      - name: install dependencies
        run: |
          npm i
          npm run build-storybook

      - name: github pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        width:
          build_dir: build
